export type TextSource = 'gutenberg' | 'wikisource' | 'vatican';

export interface CatalogueEntry {
  title: string;
  author: string;
  description: string;
  /** Omitted for pendingRights entries — source fetcher is not yet wired for 'vatican' */
  source?: TextSource;
  gutenbergId?: number;
  wikisourceTitle?: string;
  /** Fetch and concatenate multiple individual Wikisource pages (for collected works with no index page) */
  wikisourceTitles?: string[];
  /** Absent for non-LibriVox audio sources or pendingRights entries */
  librivoxAudioUrl?: string;
  /** Non-LibriVox audio source URL (e.g. Vatican News podcast page) — for reference/future ingestion */
  externalAudioUrl?: string;
  /** When true, ingestAll() skips this entry — used for titles awaiting rights authorization */
  pendingRights?: boolean;
  /** Override search string passed to LibriVox API when the full title doesn't match */
  librivoxSearchTitle?: string;
  /** Hardcoded cover image URL — skips Open Library search when present */
  coverUrl?: string;
  /** Collection this book belongs to (sets books.collection and filters from general catalog) */
  collection?: string;
  /** BCP-47 language code of the ingested text — defaults to 'es' if omitted */
  language?: string;
  /**
   * First line/phrase of the actual narrative. Everything before this pattern
   * (preamble, scholarly introduction, publisher info) is stripped from the
   * stored text so the aligner sees only content that is actually read aloud.
   */
  narrativeStartPattern?: string;
  /**
   * Marker that ends the narrative. Everything from this pattern onward
   * (glossaries, indexes, appendices) is stripped from the stored text.
   */
  narrativeEndPattern?: string;
  /**
   * Optional post-processing applied to the fetched text before storage and
   * phrase splitting. Use to strip non-spoken elements (verse line numbers,
   * illustration captions) that appear in the source but are absent from the
   * audio recording.
   */
  textPostProcess?: (text: string) => string;
}

export const CATALOGUE: CatalogueEntry[] = [
  {
    title: 'Lazarillo de Tormes',
    author: 'Anónimo',
    description: 'Novela picaresca anónima del siglo XVI, fundadora del género en la literatura española.',
    source: 'wikisource',
    wikisourceTitle: 'El Lazarillo de Tormes',
    librivoxAudioUrl: 'https://librivox.org/lazarillo-de-tormes/',
  },
  {
    title: 'El Sombrero de Tres Picos',
    author: 'Pedro Antonio de Alarcón',
    description: 'Comedia costumbrista del siglo XIX basada en una historia popular andaluza.',
    source: 'wikisource',
    wikisourceTitle: 'El sombrero de tres picos (1874)',
    librivoxAudioUrl: 'https://librivox.org/el-sombrero-de-tres-picos-by-pedro-antonio-de-alarcon-y-ariza/',
    librivoxSearchTitle: 'Sombrero de Tres Picos',
  },
  {
    title: 'Leyendas',
    author: 'Gustavo Adolfo Bécquer',
    description: 'Colección de leyendas románticas del poeta y narrador sevillano del siglo XIX.',
    source: 'wikisource',
    wikisourceTitles: [
      'El monte de las ánimas',
      'Maese Pérez el organista',
      'El rayo de luna',
      'La ajorca de oro',
      'El miserere (Bécquer)',
      'La rosa de pasión',
      'El beso',
      'El Cristo de la calavera',
      'La promesa',
      'Los ojos verdes',
      'El gnomo',
      'La corza blanca',
      'La cruz del Diablo',
      'La cueva de la mora',
      'Creed en Dios',
      'El caudillo de las manos rojas',
    ],
    librivoxAudioUrl: 'https://librivox.org/leyendas-by-gustavo-adolfo-becquer/',
  },
  {
    title: 'Don Juan Tenorio',
    author: 'José Zorrilla',
    description: 'Drama romántico en verso sobre el legendario seductor español.',
    source: 'wikisource',
    wikisourceTitle: 'Don Juan Tenorio (1844)',
    librivoxAudioUrl: 'https://librivox.org/don-juan-by-jose-zorrilla-y-moral/',
  },
  {
    title: 'Marianela',
    author: 'Benito Pérez Galdós',
    description: 'Novela social de Galdós que explora la belleza, la pobreza y el amor en la España rural.',
    source: 'wikisource',
    wikisourceTitle: 'Marianela',
    librivoxAudioUrl: 'https://librivox.org/marianela-by-benito-perez-galdos/',
  },
  {
    title: 'Doña Perfecta',
    author: 'Benito Pérez Galdós',
    description: 'Novela que denuncia el fanatismo religioso y la intolerancia en la España del siglo XIX.',
    source: 'wikisource',
    wikisourceTitle: 'Doña Perfecta',
    librivoxAudioUrl: 'https://librivox.org/dona-perfecta-by-benito-perez-galdos/',
  },
  {
    title: 'Niebla',
    author: 'Miguel de Unamuno',
    description: 'Nivola existencialista en la que el protagonista cuestiona su propia realidad ante su creador.',
    source: 'gutenberg',
    gutenbergId: 49836,
    librivoxAudioUrl: 'https://librivox.org/niebla-by-miguel-de-unamuno/',
    narrativeStartPattern: '\nPRÓLOGO\n',
    narrativeEndPattern: '—¡Y luego dirán que no matan las penas!',
  },
  {
    title: 'El Gaucho Martín Fierro',
    author: 'José Hernández',
    description: 'Poema épico gauchesco argentino, símbolo de la identidad nacional latinoamericana.',
    source: 'gutenberg',
    gutenbergId: 14765,
    librivoxAudioUrl: 'https://librivox.org/el-gaucho-martin-fierro-by-jose-hernandez/',
    librivoxSearchTitle: 'Martin Fierro',
  },
  {
    title: 'Cuentos de Amor de Locura y de Muerte',
    author: 'Horacio Quiroga',
    description: 'Cuentos del maestro rioplatense del género, ambientados en la selva misionera.',
    source: 'gutenberg',
    gutenbergId: 13507,
    librivoxAudioUrl: 'https://librivox.org/cuentos-de-amor-de-locura-y-de-muerte-by-horacio-quiroga/',
  },
  {
    title: 'Los Cuatro Jinetes del Apocalipsis',
    author: 'Vicente Blasco Ibáñez',
    description: 'Novela antibélica ambientada en la Primera Guerra Mundial, bestseller mundial de 1916.',
    source: 'gutenberg',
    gutenbergId: 24536,
    librivoxAudioUrl: 'https://librivox.org/los-cuatro-jinetes-del-apocalipsis-by-vicente-blasco-ibanez/',
    librivoxSearchTitle: 'Cuatro Jinetes',
  },
  {
    title: 'La Isla del Tesoro',
    author: 'Robert Louis Stevenson',
    description: 'Clásico de aventuras piratas narrado por el joven Jim Hawkins en busca de un tesoro oculto.',
    source: 'wikisource',
    wikisourceTitle: 'La isla del tesoro (Manuel Caballero)',
    librivoxAudioUrl: 'https://librivox.org/la-isla-del-tesoro-by-robert-louis-stevenson/',
    librivoxSearchTitle: 'Isla del Tesoro',
  },
  {
    title: 'Viaje al Centro de la Tierra',
    author: 'Julio Verne',
    description: 'Novela de ciencia ficción en la que el profesor Lidenbrock y su sobrino descienden al interior de la Tierra.',
    source: 'wikisource',
    wikisourceTitle: 'Viaje al centro de la Tierra',
    librivoxAudioUrl: 'https://librivox.org/viaje-al-centro-de-la-tierra-by-jules-verne/',
  },
  {
    title: 'Romeo y Julieta',
    author: 'William Shakespeare',
    description: 'La más célebre tragedia de amor de la literatura universal.',
    source: 'wikisource',
    wikisourceTitle: 'Romeo y Julieta (Menéndez y Pelayo tr.)',
    librivoxAudioUrl: 'https://librivox.org/romeo-y-julieta-by-william-shakespeare/',
  },
  {
    title: 'Crimen y Castigo',
    author: 'Fiódor Dostoyevski',
    description: 'Novela psicológica sobre un estudiante que comete un crimen y lidia con su conciencia.',
    source: 'gutenberg',
    gutenbergId: 61851,
    librivoxAudioUrl: 'https://librivox.org/crimen-y-castigo-by-fyodor-dostoyevsky/',
  },
  {
    title: 'La Odisea',
    author: 'Homero',
    description: 'Epopeya griega sobre el largo viaje de Odiseo de regreso a Ítaca tras la guerra de Troya.',
    source: 'gutenberg',
    gutenbergId: 58221,
    librivoxAudioUrl: 'https://librivox.org/la-odisea-by-homero/',
    librivoxSearchTitle: 'Odisea',
    // Gutenberg 58221 has a long scholarly preamble (AL LECTOR + NOTAS) before Canto I
    // and a 1700-entry glossary (ÍNDICE DE NOMBRES PROPIOS) after FIN.
    // Both sections are absent from the LibriVox audio.
    narrativeStartPattern: 'CANTO PRIMERO',
    narrativeEndPattern: '\nFIN\n',
    textPostProcess: (text: string) => {
      // Remove [Ilustración ...] captions — not read aloud, may span multiple lines
      let cleaned = text.replace(/\[Ilustración[^\[]*?\]/g, '');
      // Remove verse line numbers at paragraph starts (Greek line refs, e.g. "1 Háblame")
      cleaned = cleaned.replace(/^\d{1,4} /gm, '');
      // Collapse blank lines left by removed content
      cleaned = cleaned.replace(/\n{3,}/g, '\n\n');
      return cleaned.trim();
    },
  },
  {
    title: 'La Divina Comedia',
    author: 'Dante Alighieri',
    description: 'Poema épico medieval que narra el viaje de Dante por el Infierno, el Purgatorio y el Paraíso.',
    source: 'gutenberg',
    gutenbergId: 57303,
    librivoxAudioUrl: 'https://librivox.org/la-divina-comedia-by-dante-alighieri/',
    librivoxSearchTitle: 'Divina Comedia',
  },
  {
    title: 'Don Quijote de la Mancha — Vol. I',
    author: 'Miguel de Cervantes',
    description: 'Primera parte de la obra cumbre de la literatura española y universal.',
    source: 'gutenberg',
    gutenbergId: 2000,
    librivoxAudioUrl: 'https://librivox.org/don-quijote-vol-1-by-miguel-de-cervantes-saavedra/',
    librivoxSearchTitle: 'Don Quijote',
  },
  {
    title: 'Don Quijote de la Mancha — Vol. II',
    author: 'Miguel de Cervantes',
    description: 'Segunda parte de la inmortal novela del caballero manchego y su escudero Sancho Panza.',
    source: 'gutenberg',
    gutenbergId: 2000,
    librivoxAudioUrl: 'https://librivox.org/don-quijote-volume-2-by-miguel-de-cervantes-saavedra/',
    librivoxSearchTitle: 'Don Quijote',
  },
  {
    title: 'Orgullo y Prejuicio',
    author: 'Jane Austen',
    description: 'Novela de la escritora inglesa sobre el amor, el matrimonio y los prejuicios sociales en la Inglaterra del siglo XIX.',
    source: 'wikisource',
    wikisourceTitle: 'Orgullo y prejuicio',
    librivoxAudioUrl: 'https://librivox.org/orgullo-y-prejuicio1-by-jane-austen/',
    librivoxSearchTitle: 'Orgullo Prejuicio',
  },
  {
    title: 'Génesis',
    author: 'Anónimo',
    description: 'El primer libro del Antiguo Testamento: la creación del mundo, Adán y Eva, Noé, Abraham, Isaac, Jacob y José. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Génesis',
    librivoxAudioUrl: 'https://librivox.org/genesis-reina-valera-version/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Salmos',
    author: 'Anónimo',
    description: 'La gran colección de cánticos y oraciones del pueblo de Israel: 150 salmos de alabanza, lamento, gratitud y confianza en Dios. Versión Reina-Valera.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Salmos',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-antigua-19-salmos-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Mateo',
    author: 'Anónimo',
    description: 'El primer evangelio: la vida, enseñanzas, muerte y resurrección de Jesucristo, presentado como el Mesías prometido a Israel. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Mateo',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-01-mateo-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Juan',
    author: 'Anónimo',
    description: 'El cuarto evangelio, centrado en la divinidad de Jesús. Incluye Juan 3:16, los siete milagros y las declaraciones "Yo soy" de Cristo. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Juan',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-04-juan-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Romanos',
    author: 'Anónimo',
    description: 'La carta más sistemática de Pablo: la justificación por la fe, el poder del Espíritu y la vida cristiana en comunidad. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Romanos',
    librivoxAudioUrl: 'https://librivox.org/bible-nt-06-romanos-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Marcos',
    author: 'Anónimo',
    description: 'El evangelio más breve y dinámico: la vida de Jesús narrada con urgencia y acción, desde su bautismo hasta su resurrección. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Marcos',
    librivoxAudioUrl: 'https://librivox.org/el-bible-reina-valera-nt-02-evangelio-segun-marcos-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Lucas',
    author: 'Anónimo',
    description: 'El evangelio más extenso: relato detallado de la vida de Jesús, con especial énfasis en los pobres, las mujeres y la misericordia divina. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Lucas',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-03-lucas-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Hechos',
    author: 'Anónimo',
    description: 'La historia de la iglesia primitiva: el Espíritu Santo en Pentecostés, los apóstoles y los viajes misioneros de Pablo por el mundo mediterráneo. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Hechos',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-05-hechos-de-los-apostoles-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: '1 Corintios',
    author: 'Anónimo',
    description: 'La carta de Pablo a una iglesia dividida: unidad, el himno al amor, los dones espirituales y la resurrección de Cristo. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/1 Corintios',
    librivoxAudioUrl: 'https://librivox.org/1-corintios-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Efesios',
    author: 'Anónimo',
    description: 'Pablo describe la iglesia como cuerpo de Cristo: la gracia, la unidad entre judíos y gentiles, y la armadura de Dios. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Efesios',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-10-la-epistola-del-apostol-san-pablo-a-los-efesios-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Filipenses',
    author: 'Anónimo',
    description: 'La carta de la alegría: Pablo desde prisión anima a los creyentes a regocijarse en Cristo y a buscar la paz que sobrepasa todo entendimiento. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Filipenses',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-11-filipenses-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Hebreos',
    author: 'Anónimo',
    description: 'Jesús como sumo sacerdote eterno: argumentación teológica sobre la superioridad del nuevo pacto y el llamado a la fe perseverante. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Hebreos',
    librivoxAudioUrl: 'https://librivox.org/hebreos-version-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Santiago',
    author: 'Anónimo',
    description: 'Fe sin obras es muerta: enseñanza práctica sobre la vida cristiana, la sabiduría, la oración y el cuidado de los pobres. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Santiago',
    librivoxAudioUrl: 'https://librivox.org/carta-del-apostol-santiago-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Apocalipsis',
    author: 'Anónimo',
    description: 'La visión de Juan en Patmos: cartas a las siete iglesias, los sellos, las trompetas y la Nueva Jerusalén al final de los tiempos. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Apocalipsis',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-nt-27-apocalipsis-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Éxodo',
    author: 'Anónimo',
    description: 'La liberación de Israel de Egipto: Moisés, las diez plagas, el paso del Mar Rojo y la entrega de los Diez Mandamientos en el Sinaí. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Éxodo',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-02-exodo-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Proverbios',
    author: 'Anónimo',
    description: '31 capítulos de sabiduría práctica atribuida a Salomón: consejos sobre la familia, el trabajo, la honestidad y el temor a Dios. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Proverbios',
    librivoxAudioUrl: 'https://librivox.org/bible-reina-valera-1909-20-libro-de-los-proverbios-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },
  {
    title: 'Isaías',
    author: 'Anónimo',
    description: 'El gran profeta del Antiguo Testamento: mensajes de juicio y restauración para Israel, y las profecías del Siervo Sufriente. Versión Reina-Valera 1909.',
    source: 'wikisource',
    wikisourceTitle: 'Biblia Reina-Valera 1909/Isaías',
    librivoxAudioUrl: 'https://librivox.org/isaias-by-reina-valera/',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
  },

  {
    title: 'Platero y yo',
    author: 'Juan Ramón Jiménez',
    description: 'Elegía andaluza en prosa lírica sobre la amistad entre un poeta y su burro Platero en Moguer. Nobel de Literatura 1956.',
    source: 'gutenberg',
    gutenbergId: 39209,
    librivoxAudioUrl: 'https://librivox.org/platero-y-yo-by-juan-ramon-jimenez/',
    librivoxSearchTitle: 'Platero',
  },
  {
    title: 'Pepita Jiménez',
    author: 'Juan Valera',
    description: 'Novela epistolar en la que un joven seminarista descubre que el amor humano puede ser tan sagrado como la vocación religiosa.',
    source: 'gutenberg',
    gutenbergId: 17223,
    librivoxAudioUrl: 'https://librivox.org/pepita-jimenez-by-juan-valera/',
    librivoxSearchTitle: 'Pepita Jiménez',
  },

  // ── English Classics ──────────────────────────────────────────────────────

  {
    title: 'Treasure Island',
    author: 'Robert Louis Stevenson',
    description: 'A young boy discovers a treasure map and sails to a remote island with a crew harboring deadly secrets — the definitive pirate adventure.',
    source: 'gutenberg',
    gutenbergId: 120,
    librivoxAudioUrl: 'https://librivox.org/treasure-island-by-robert-louis-stevenson/',
    language: 'en',
  },
  {
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    description: 'The spirited Elizabeth Bennet navigates love, family, and social convention in Regency England — Austen\'s most beloved novel.',
    source: 'gutenberg',
    gutenbergId: 1342,
    librivoxAudioUrl: 'https://librivox.org/pride-and-prejudice-by-jane-austen/',
    language: 'en',
  },
  {
    title: 'The Call of the Wild',
    author: 'Jack London',
    description: 'A domesticated dog is thrust into the brutal Klondike gold rush and discovers his primal nature — London\'s masterpiece of nature and survival.',
    source: 'gutenberg',
    gutenbergId: 215,
    librivoxAudioUrl: 'https://librivox.org/call-of-the-wild-by-jack-london/',
    language: 'en',
  },
  {
    title: 'Frankenstein',
    author: 'Mary Shelley',
    description: 'Victor Frankenstein creates life from death and is haunted by his creation — the founding work of science fiction and a meditation on ambition.',
    source: 'gutenberg',
    gutenbergId: 84,
    librivoxAudioUrl: 'https://librivox.org/frankenstein-or-modern-prometheus-by-mary-w-shelley/',
    language: 'en',
  },
  {
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    description: 'A portrait ages while its subject stays young and sins freely — Wilde\'s only novel, a dark fable about beauty, corruption, and the soul.',
    source: 'gutenberg',
    gutenbergId: 174,
    librivoxAudioUrl: 'https://librivox.org/the-picture-of-dorian-gray-by-oscar-wilde/',
    language: 'en',
  },
  {
    title: 'The Strange Case of Dr Jekyll and Mr Hyde',
    author: 'Robert Louis Stevenson',
    description: 'A respected doctor unleashes a murderous alter ego — a chilling exploration of duality and the shadow self.',
    source: 'gutenberg',
    gutenbergId: 43,
    librivoxAudioUrl: 'https://librivox.org/the-strange-case-of-dr-jekyll-and-mr-hyde-by-robert-louis-stevenson/',
    language: 'en',
  },
  {
    title: 'The Adventures of Tom Sawyer',
    author: 'Mark Twain',
    description: 'Tom Sawyer\'s boyhood pranks on the Mississippi River — witnessing a murder, searching for treasure, and finding love.',
    source: 'gutenberg',
    gutenbergId: 74,
    librivoxAudioUrl: 'https://librivox.org/tom-sawyer-by-mark-twain/',
    language: 'en',
  },
  {
    title: "Alice's Adventures in Wonderland",
    author: 'Lewis Carroll',
    description: 'A girl tumbles down a rabbit hole into a world of impossible logic — Carroll\'s timeless fantasy that invented literary nonsense.',
    source: 'gutenberg',
    gutenbergId: 11,
    librivoxAudioUrl: 'https://librivox.org/alices-adventures-in-wonderland-by-lewis-carroll/',
    language: 'en',
  },
  {
    title: 'The Time Machine',
    author: 'H. G. Wells',
    description: 'A Victorian inventor travels 800,000 years into the future and discovers a humanity divided into two frightening species.',
    source: 'gutenberg',
    gutenbergId: 35,
    librivoxAudioUrl: 'https://librivox.org/the-time-machine-by-hg-wells/',
    language: 'en',
  },
  {
    title: 'Anne of Green Gables',
    author: 'L. M. Montgomery',
    description: 'An orphan girl with a vivid imagination finds a home and family on Prince Edward Island — one of literature\'s most beloved coming-of-age stories.',
    source: 'gutenberg',
    gutenbergId: 45,
    librivoxAudioUrl: 'https://librivox.org/anne-of-green-gables-by-lucy-maud-montgomery/',
    language: 'en',
  },
  {
    title: 'Dracula',
    author: 'Bram Stoker',
    description: 'A solicitor travels to Transylvania and encounters the undead — Stoker\'s epistolary masterpiece that defined the vampire in modern culture.',
    source: 'gutenberg',
    gutenbergId: 345,
    librivoxAudioUrl: 'https://librivox.org/dracula-by-bram-stoker/',
    language: 'en',
  },
  {
    title: 'The Scarlet Letter',
    author: 'Nathaniel Hawthorne',
    description: 'A woman in Puritan Boston bears a scarlet A for adultery while the true sinner hides in plain sight — Hawthorne\'s masterwork on guilt and redemption.',
    source: 'gutenberg',
    gutenbergId: 25344,
    librivoxAudioUrl: 'https://librivox.org/the-scarlet-letter-by-nathaniel-hawthorne/',
    language: 'en',
  },

  {
    title: 'Meditations',
    author: 'Marcus Aurelius',
    description: 'Personal reflections of the Roman Emperor Marcus Aurelius — the definitive Stoic guide to resilience, duty, and the art of living with purpose.',
    source: 'gutenberg',
    gutenbergId: 2680,
    language: 'en',
    librivoxAudioUrl: 'https://librivox.org/the-meditations-of-marcus-aurelius/',
    librivoxSearchTitle: 'Meditations Marcus Aurelius',
    narrativeStartPattern: 'THE FIRST BOOK',
    narrativeEndPattern: '\nAPPENDIX\n',
  },
  {
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    description: 'A plain-spoken orphan grows into a fiercely independent woman — Brontë\'s masterwork on love, identity, and the courage to refuse compromise.',
    source: 'gutenberg',
    gutenbergId: 1260,
    language: 'en',
    librivoxAudioUrl: 'https://librivox.org/jane-eyre-by-charlotte-bront/',
    librivoxSearchTitle: 'Jane Eyre',
  },

  // ── English Bible (KJV) — collection: 'Bible' ─────────────────────────────

  {
    title: 'Genesis',
    author: 'Anonymous',
    description: 'The first book of the Old Testament: creation, Adam and Eve, Noah, Abraham, Isaac, Jacob, and Joseph. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Genesis',
    librivoxAudioUrl: 'https://librivox.org/bible-kjv-01-03-genesis-exodus-and-leviticus/',
    librivoxSearchTitle: 'King James Bible Genesis',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Exodus',
    author: 'Anonymous',
    description: 'Israel\'s liberation from Egypt: Moses, the ten plagues, the parting of the Red Sea, and the Ten Commandments at Sinai. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Exodus',
    librivoxAudioUrl: 'https://librivox.org/bible-kjv-01-03-genesis-exodus-and-leviticus/',
    librivoxSearchTitle: 'King James Bible Exodus',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Psalms',
    author: 'Anonymous',
    description: '150 poems of praise, lament, trust, and thanksgiving — the prayer book of ancient Israel and the most-read book of the Bible. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Psalms',
    librivoxAudioUrl: 'https://librivox.org/the-book-of-psalms-king-james-version/',
    librivoxSearchTitle: 'King James Bible Psalms',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Proverbs',
    author: 'Anonymous',
    description: '31 chapters of practical wisdom on family, work, honesty, and the fear of God, attributed to Solomon. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Proverbs',
    librivoxAudioUrl: 'https://librivox.org/proverbs-king-james-version/',
    librivoxSearchTitle: 'King James Bible Proverbs',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Isaiah',
    author: 'Anonymous',
    description: 'The great prophet of the Old Testament: messages of judgment and restoration for Israel, and the Suffering Servant prophecies. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Isaiah',
    librivoxAudioUrl: 'https://librivox.org/isaiah-king-james-version/',
    librivoxSearchTitle: 'King James Bible Isaiah',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Matthew',
    author: 'Anonymous',
    description: 'The first Gospel: the life, teachings, death, and resurrection of Jesus Christ, presented as the promised Messiah. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Matthew',
    librivoxAudioUrl: 'https://librivox.org/matthew-king-james-version/',
    librivoxSearchTitle: 'King James Bible Matthew',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Mark',
    author: 'Anonymous',
    description: 'The shortest and most urgent Gospel — the life of Jesus narrated with action and immediacy from baptism to resurrection. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Mark',
    librivoxAudioUrl: 'https://librivox.org/gospel-of-mark-king-james-version/',
    librivoxSearchTitle: 'King James Bible Mark',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Luke',
    author: 'Anonymous',
    description: 'The most detailed Gospel, with special emphasis on the poor, women, and the mercy of God — includes the parables of the prodigal son and good Samaritan. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Luke',
    librivoxAudioUrl: 'https://librivox.org/bible-kjv-nt-03-luke/',
    librivoxSearchTitle: 'King James Bible Luke',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'John',
    author: 'Anonymous',
    description: 'The fourth Gospel, focused on the divinity of Jesus. Includes John 3:16, the seven signs, and the great "I am" sayings. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/John',
    librivoxAudioUrl: 'https://librivox.org/john-by-king-james-version/',
    librivoxSearchTitle: 'King James Bible John',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Acts',
    author: 'Anonymous',
    description: 'The history of the early church: the Holy Spirit at Pentecost, the apostles, and Paul\'s missionary journeys across the Mediterranean world. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Acts',
    librivoxAudioUrl: 'https://librivox.org/acts-king-james-version/',
    librivoxSearchTitle: 'King James Bible Acts',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Romans',
    author: 'Anonymous',
    description: 'Paul\'s most systematic letter: justification by faith, the power of the Spirit, and Christian life in community. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Romans',
    librivoxAudioUrl: 'https://librivox.org/romans-king-james-version/',
    librivoxSearchTitle: 'King James Bible Romans',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: '1 Corinthians',
    author: 'Anonymous',
    description: 'Paul\'s letter to a divided church: unity, the hymn to love (chapter 13), spiritual gifts, and the resurrection. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/1 Corinthians',
    librivoxAudioUrl: 'https://librivox.org/1-corinthians-king-james-version/',
    librivoxSearchTitle: 'King James Bible 1 Corinthians',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Ephesians',
    author: 'Anonymous',
    description: 'Paul describes the church as the body of Christ: grace, unity between Jews and Gentiles, and the armor of God. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Ephesians',
    librivoxAudioUrl: 'https://librivox.org/4-epistles-king-james-version/',
    librivoxSearchTitle: 'King James Bible Ephesians',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Philippians',
    author: 'Anonymous',
    description: 'The letter of joy: Paul from prison encourages believers to rejoice in Christ and seek the peace that passes all understanding. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Philippians',
    librivoxAudioUrl: 'https://librivox.org/4-epistles-king-james-version/',
    librivoxSearchTitle: 'King James Bible Philippians',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Hebrews',
    author: 'Anonymous',
    description: 'Jesus as eternal high priest — a theological argument for the superiority of the new covenant and a call to persevering faith. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Hebrews',
    librivoxAudioUrl: 'https://librivox.org/hebrews-king-james-version/',
    librivoxSearchTitle: 'King James Bible Hebrews',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'James',
    author: 'Anonymous',
    description: 'Faith without works is dead — practical teaching on Christian living, wisdom, prayer, and care for the poor. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/James',
    librivoxAudioUrl: 'https://librivox.org/book-of-james-kjv/',
    librivoxSearchTitle: 'King James Bible James',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },
  {
    title: 'Revelation',
    author: 'Anonymous',
    description: 'John\'s vision on Patmos: letters to the seven churches, the seals and trumpets, and the New Jerusalem at the end of time. King James Version.',
    source: 'wikisource',
    wikisourceTitle: 'Bible (King James)/Revelation',
    librivoxAudioUrl: 'https://librivox.org/revelation-king-james-version/',
    librivoxSearchTitle: 'King James Bible Revelation',
    coverUrl: 'https://covers.openlibrary.org/b/id/12324628-L.jpg',
    collection: 'Bible',
    language: 'en',
  },

  // ── Literatura Infantil ────────────────────────────────────────────────────

  {
    title: 'Fábulas y Verdades',
    author: 'Rafael Pombo',
    description:
      'La obra más querida del poeta colombiano: fábulas en verso para niños que incluyen El Renacuajo Paseador, Simón el Bobito, La Pobre Viejecita y Mirringa Mirronga. Dominio público.',
    source: 'wikisource',
    wikisourceTitles: [
      'El renacuajo paseador',
      'Simón el bobito',
      'La pobre viejecita',
      'Mirringa Mirronga',
      'El gato bandido',
      'Pastorcita',
      'Cutufato y su gato',
      'El búho y el palomo',
      'El niño y la mariposa',
      'La marrana peripuesta',
      'El coche',
    ],
    librivoxAudioUrl: 'https://librivox.org/fabulas-y-verdades-by-rafael-pombo/',
    coverUrl: '/covers/fabulas-pombo.png',
  },
  {
    title: 'Cuentos de la Selva',
    author: 'Horacio Quiroga',
    description:
      'Ocho cuentos para niños ambientados en la selva misionera: La Abeja Haragana, Las Medias de los Flamencos, La Tortuga Gigante y más. Obra hermana de los Cuentos de Amor ya disponibles en Noetia. Dominio público.',
    source: 'wikisource',
    wikisourceTitles: [
      'La tortuga gigante',
      'Las medias de los flamencos',
      'El loro pelado',
      'La guerra de los yacarés',
      'La abeja haragana',
      'Historia de dos cachorros de coatí y de dos cachorros de hombre',
      'La gama ciega',
      'El paso del Yabebirí',
    ],
    librivoxAudioUrl: 'https://librivox.org/cuentos-de-la-selva-para-los-ninos-by-horacio-quiroga/',
    librivoxSearchTitle: 'Cuentos de la Selva',
    coverUrl: '/covers/cuentos-selva.png',
  },

  // ── Pending rights — do NOT ingest until authorization is confirmed ────────

  // Rights request sent 2026-06-10 to diritti.lev@spc.va (LEV Ufficio Diritti) from pronoiallc@gmail.com.
  // Requested: free reproduction of full text, Vatican News EN audio licensing, advance auth for future ES audio.
  // Text source: https://www.vatican.va/content/leo-xiv/es/encyclicals/documents/20260515-magnifica-humanitas.html
  // Audio: no Spanish recording exists as of 2026-06-10.
  {
    pendingRights: true,
    source: 'vatican',
    title: 'Magnifica Humanitas',
    author: 'León XIV',
    description:
      'Carta encíclica del Papa León XIV sobre la salvaguarda de la persona humana en tiempos de inteligencia artificial. Introducción + 5 capítulos + Conclusión; 245 párrafos; ~37.000 palabras.',
    language: 'es',
  },

  // Rights request sent 2026-06-10 to diritti.lev@spc.va (LEV Ufficio Diritti) from pronoiallc@gmail.com.
  // Text source: https://www.vatican.va/content/leo-xiv/en/encyclicals/documents/20260515-magnifica-humanitas.html
  // Audio: Vatican News EN audiobook (7 files, ~4.5–6h, narrator Sr. Bernadette Reis FSP) — licensing TBD.
  {
    pendingRights: true,
    source: 'vatican',
    title: 'Magnifica Humanitas',
    author: 'Leo XIV',
    description:
      'Encyclical letter of Pope Leo XIV on safeguarding the human person in the time of artificial intelligence. Introduction + 5 chapters + Conclusion; 245 paragraphs; ~37,000 words.',
    language: 'en',
    externalAudioUrl: 'https://www.vaticannews.va/en/podcast/magnifica-humanitas.html',
  },
];
